eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url: http://localhost:8765/swagger-ui.html

server:
  port: 8765

spring:
  application:
    name: service-feign

# Feign自带断路器, 配置默认是关闭的,
# 打开断路器
feign.hystrix.enabled: true