server:
  port: 8762

eureka:
  client:
    service-url:
      #这一步是往Apollo的Erueka上注册服务
      defaultZone: http://localhost:8080/eureka/
  instance:
    status-page-url: http://localhost:8762/swagger-ui.html
# ${server.port}为该服务的端口号
#eureka.instance.status-page-url=http://localhost:${server.port}/swagger-ui.html

spring:
  application:
    name: eureka-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cocacola
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   #ddl-auto:设为create表示每次都重新建表
    show-sql: true