eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url: http://localhost:8764/swagger-ui.html

server:
  port: 8764

spring:
  application:
    name: service-ribbon